### ISSUE TITLE
dark mode in Nuxt3

### ISSUE THREAD

**Issue by tasiotas** [inkline/inkline#293]
* **What is the expected and current behavior?**
  Initial class assignment for color modes is wrong when page loads. Once I toggle between dark/light modes, classes are set correctly.

* **Steps to reproduce**
  Open minimal starter in StackBlitz. Take a look at "invisible" labels on checkbox and toggle. 
  https://stackblitz.com/edit/nuxt-starter-7vdjmd?file=app.vue

  Please set your preferred browser color scheme to dark.

* **Please tell us about your environment:**
    "nuxt": "3.0.0-rc.4",
    "sass": "^1.52.3"
    "@inkline/inkline": "^3.0.9",
    "@inkline/nuxt": "^3.1.3"

**Comment by tasiotas** [comment]
hi @alexgrozav , I am really stuck with this one. <i-toggle> and <i-checkbox> (potentially more) are having problem with dark mode.
When `colorMode: 'system'`, those components render incorrectly when browser preferred color scheme is set to dark.

On page load:
![image](https://user-images.githubusercontent.com/9046931/179427128-501b12ed-a74e-431e-b237-8b6f9b9f9b96.png)

After clicking button to toggle color modes:
![image](https://user-images.githubusercontent.com/9046931/179427147-20b190c1-b508-4151-b057-7f2ff7b74562.png)

Thank you

**Comment by tasiotas** [comment]
hi @alexgrozav , have you had a chance to take a look at this?
It's preventing me from using dark theme on my website, and I have no clue what is causing it.

thank you

**Comment by alexgrozav** [comment]
Sorry, I haven't had the chance to look at it. I'll try to see what's happening tomorrow.

**Comment by alexgrozav** [comment]
Hey! I've looked into it. The bug is caused by `inklineGlobals` not being available at the time of calling `defaultPropValue` in SSR. This is fixed in Inkline 4 by providing the default color and default size using a computed prop. 

If you have the time and would like to backport it into Inkline 3, I'd appreciate a PR. 

Component Example here: https://github.com/inkline/inkline/blob/ab1ae95860b417a298106e01621d73a3fdfae3a3/src/components/IProgress/script.ts

**Comment by tasiotas** [comment]
Hi,
Thanks for explanation and pointer to the code.

I forked repo and started dev server. Were you able to reproduce this behavior in dev with Storybook? It looks ok in dark mode before I even toggle light/dark in Story's UI.

**Comment by alexgrozav** [comment]
@tasiotas Unfortunately you can't reproduce it in Storybook. This only happens when Server Side Rendering is used. 🫤

**Comment by alexgrozav** [comment]
Here's an example on how to create a color mode switcher that works with Inkline 4 + Nuxt 3: https://github.com/inkline/inkline.io/blob/main/components/app/ColorModeSwitcher.vue

**Comment by Lexpeartha** [comment]
> Here's an example on how to create a color mode switcher that works with Inkline 4 + Nuxt 3: https://github.com/inkline/inkline.io/blob/main/components/app/ColorModeSwitcher.vue

I'm replicating the dark mode in the exact same way but [this](https://nuxt-inkline-test.netlify.app/) is what I'm getting (notice the footer on the fresh loads). This bug is still reproducible even on nuxt 3.11 and inkline 4.7
